### PR TITLE
Issue #448: Add pre-commit hook to run "npm run lint" before commiting

### LINKED ISSUE #448: Add git hooks for linting
People often forget about checking code styling before pushing up a change. Husky (https://github.com/typicode/husky/tree/master) allows for easy set up of precommit and prepush hooks. I am going to install this and set up a precommit hook for linting the project

### PR DESCRIPTION
**Pull request by alexanderturinske**
Used Husky (https://github.com/typicode/husky/tree/master) to implement precommit linting
Fixes #448

### CODE REVIEW

**Comment by alexanderturinske** [comment]
Don't merge this. It is up for debate.

**Comment by lgarofalo** [comment]
@alexanderturinske Seems good, what is the debate?

**Comment by lexholden** [comment]
Actually surprised to not have noticed we didn't already have this. Definitely +1, is invaluable in every other project I work on professionally.

**Comment by alexanderturinske** [comment]
Well, I just found out we have this in our CI, so I don't think it is necessary anymore.

**Comment by lexholden** [comment]
Sure but enforcing it before people commit rather than having extra commits that are just "fixed linting errors" is definitely an improvement I'd say?

**Comment by alexanderturinske** [comment]
Okay. Sounds good to me!

**Comment by lexholden** [comment]
Going to merge this before it gets stale.

**Pull request merged**
