### PR TITLE
Fixed bug when resource doesn't exist (e.g. new resource page)

### PR DESCRIPTION
**Pull request by lexholden**
Fixes a bug missed in #451

### CODE REVIEW

**Comment by lexholden** [comment]
So @richardxia do you think we should roll back the original and remerge once both issues are fixed, or merge this and create an urgent followup issue for the additional bug you've found?

I'd suggest the latter personally, since we're about to refactor the whole page anyway.

**Comment by alexanderturinske** [comment]
Next datathon is this Saturday; will we have time to fix it by then? I can work on this tonight.

**Comment by richardxia** [comment]
If we think we can fix this with the refactoring in time for the datathon, then we don't need to rollback. Or additionally, we could just remove the "Add new resource" link entirely, if we don't think people will need to create new resources during the datathon.

**Comment by alexanderturinske** [comment]
Pushed up a modified patch which fixes the issue fully.

**Pull request merged**
