### PR TITLE
New landing page (WIP)

### PR DESCRIPTION
**Pull request by richardxia**
This is a WIP branch for implementing #873. I have the header nav, hero, search, and categories list components converted over. Still left to do are the Guided Pathways section, which I believe @quanhuynh is working on, the Partners section, and the minor change to the footer (I think just the background color).

Note that none of these changes are responsive, and the page looks pretty bad on mobile.

Screen Shot 2019-10-06 at 10 16 12 PM

Behind the scenes, I'd like to mention that I'm trying out a new directory structure, which hopefully makes it easier to find components in the future. Basically, I put the HomePage JSX and SCSS into a directory, and I also put any components that are specific to the home page in subdirectories within that directory. All of the directories contain an `index.jsx`, which is mostly just for import path purposes, and JSX and SCSS files for each component. Here's an ASCII art diagram, which I think will make things a bit clearer:

```
app/pages/HomePage/
|-- HomePage.jsx
|-- components
|   |-- CategoryList
|   |   |-- CategoryList.jsx
|   |   |-- CategoryList.scss
|   |   `-- index.js
|   |-- HomePageHero
|   |   |-- HomePageHero.jsx
|   |   |-- HomePageHero.scss
|   |   `-- index.js
|   |-- SearchBar
|   |   |-- SearchBar.jsx
|   |   |-- SearchBar.scss
|   |   `-- index.js
|   `-- Section
|       |-- Section.jsx
|       |-- Section.scss
|       `-- index.js
`-- index.js
```

### CODE REVIEW

**Comment by derekfidler** [comment]
Nice work. I’ll get a mobile design completed today.

> On 7 Oct 2019, at 07:23, Richard Xia <notifications@github.com> wrote:
> 

﻿
This is a WIP branch for implementing #873. I have the header nav, hero, search, and categories list components converted over. Still left to do are the Guided Pathways section, which I believe @quanhuynh is working on, the Partners section, and the minor change to the footer (I think just the background color).

Note that none of these changes are responsive, and the page looks pretty bad on mobile.



Behind the scenes, I'd like to mention that I'm trying out a new directory structure, which hopefully makes it easier to find components in the future. Basically, I put the HomePage JSX and SCSS into a directory, and I also put any components that are specific to the home page in subdirectories within that directory. All of the directories contain an index.jsx, which is mostly just for import path purposes, and JSX and SCSS files for each component. Here's an ASCII art diagram, which I think will make things a bit clearer:

app/pages/HomePage/
|-- HomePage.jsx
|-- components
|   |-- CategoryList
|   |   |-- CategoryList.jsx
|   |   |-- CategoryList.scss
|   |   `-- index.js
|   |-- HomePageHero
|   |   |-- HomePageHero.jsx
|   |   |-- HomePageHero.scss
|   |   `-- index.js
|   |-- SearchBar
|   |   |-- SearchBar.jsx
|   |   |-- SearchBar.scss
|   |   `-- index.js
|   `-- Section
|       |-- Section.jsx
|       |-- Section.scss
|       `-- index.js
`-- index.js
You can view, comment on, or merge this pull request online at:

  https://github.com/ShelterTechSF/askdarcel-web/pull/876

Commit Summary

Update primary nav bar with new styles.
Move HomePage files into its own directory.
Add HomePage Hero.
Add generic HomePage Section component.
Add SearchBar component.
Remove FindHeader.
Add new CategoryList component.
Remove old CategoryList files.
Update HomePage component to pull in new components.
Remove unused HomePage.scss.
File Changes

A app/assets/img/HomePage/hero-background.svg (39)
M app/components/App.jsx (2)
D app/components/layout/CategoryItem.jsx (24)
D app/components/layout/CategoryList.jsx (14)
D app/components/layout/FindHeader.jsx (80)
D app/components/layout/FindHeader.scss (122)
M app/components/ui/Navigation.jsx (2)
M app/components/ui/Navigation.scss (9)
D app/pages/HomePage.jsx (63)
D app/pages/HomePage.scss (3)
A app/pages/HomePage/HomePage.jsx (94)
A app/pages/HomePage/components/CategoryList/CategoryList.jsx (56)
A app/pages/HomePage/components/CategoryList/CategoryList.scss (68)
A app/pages/HomePage/components/CategoryList/index.js (1)
A app/pages/HomePage/components/HomePageHero/HomePageHero.jsx (32)
A app/pages/HomePage/components/HomePageHero/HomePageHero.scss (35)
A app/pages/HomePage/components/HomePageHero/index.js (1)
A app/pages/HomePage/components/SearchBar/SearchBar.jsx (43)
A app/pages/HomePage/components/SearchBar/SearchBar.scss (40)
A app/pages/HomePage/components/SearchBar/index.js (1)
A app/pages/HomePage/components/Section/Section.jsx (27)
A app/pages/HomePage/components/Section/Section.scss (20)
A app/pages/HomePage/components/Section/index.js (1)
A app/pages/HomePage/index.js (1)
M app/routes.jsx (2)
D app/styles/components/_categorypage.scss (96)
M app/styles/main.scss (1)
M webpack.config.js (2)
Patch Links:

https://github.com/ShelterTechSF/askdarcel-web/pull/876.patch
https://github.com/ShelterTechSF/askdarcel-web/pull/876.diff

**Comment by quanhuynh** [comment]
@richardxia oh man thank you for reorganizing the folders! i was about to raise a separate issue on that

**Comment by quanhuynh** [comment]
@richardxia @derekfidler the typeform links for the guide cards still need to be updated before merge

**Comment by derekfidler** [comment]
We only have the Youth Homelessness guide available right now. Can the rest
not do anything on click for now?

I'd like to see how it feels on staging and let MOHCD check it out on
Wednesday. I believe we're doing a full screen modal and I want to make
sure that's the right solution for the integration.

**Comment by quanhuynh** [comment]
right now all of them link to the Youth Homelessness guide :)

**Comment by derekfidler** [comment]
That's fine, let's get this to staging!

**Pull request merged**
