### PR TITLE
Reset app auth state if Auth0 session has expired

### PR DESCRIPTION
**Pull request by schroerbrian**
refs https://github.com/ShelterTechSF/askdarcel-web/issues/1391

### CODE REVIEW

**Review by katerina-kossler — COMMENTED** [review]
the changes here look right from what I can tell but I see that some tests in CI are failing and I don't see any test coverage for this (is that normal for the web project?)

**Review by richardxia — APPROVED** [review]
LGTM! Though should we also actually clear that state when we detect this issue? I guess I'm thinking that if someone navigated away from the log-in page, then they'd still be in this inconsistent state where the app thinks they're logged in but their credentials have expired.

**Comment by richardxia** [comment]
> the changes here look right from what I can tell but I see that some tests in CI are failing and I don't see any test coverage for this (is that normal for the web project?)

Regrettably, it's normal for the web project to have flaky failures with the end-to-end browser tests. Normally I just restart it until it finally succeeds.

**Comment by schroerbrian** [comment]
> > the changes here look right from what I can tell but I see that some tests in CI are failing and I don't see any test coverage for this (is that normal for the web project?)
> 
> Regrettably, it's normal for the web project to have flaky failures with the end-to-end browser tests. Normally I just restart it until it finally succeeds.

Unfortunately, this failure seems to do with a deprecated artifact in our build system. I just haven’t had time to look further into this.  I’m away this weekend so i can’t work on it. Anyhow, i suppose this could be safely merged in if we want to, but i don’t mind waiting until we get to the bottom of this , either 

`Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/`

**Comment by schroerbrian** [comment]
> LGTM! Though should we also actually clear that state when we detect this issue? I guess I'm thinking that if someone navigated away from the log-in page, then they'd still be in this inconsistent state where the app thinks they're logged in but their credentials have expired.

Is there another state I’m missing? The code sets the authState to null prior to the redirect

**Comment by schroerbrian** [comment]
Thanks for the review @richardxia and @katerina-kossler ! Sorry for my late replies here

**Comment by richardxia** [comment]
> Is there another state I’m missing? The code sets the authState to null prior to the redirect

Wow, sorry, I don't know how I missed that. My brain managed to completely not see that line in between the `if` and the redirect. Yeah, sorry, this LGTM!

**Comment by schroerbrian** [comment]
I am going to go ahead and merge this in as the test failure is unrelated. Thanks all!

**Pull request merged**
